### ISSUE TITLE
Can't make it work with Prepar3d v 3.

### ISSUE THREAD

**Issue by seymurkarimov** [joeherwig/portable-sim-panels#1]
Can't make it work with Prepar3d v 3. Could you please update the script files to match P3D? Or give instructions.  This part 
Register-ObjectEvent -InputObject $global:fsx -EventName OnRecvSimobjectData -Action { 
    try { 
        $global:sim = $args.dwData[0] 
 

        $JSON = ConvertTo-Json($args.dwData[0])

        $response = Invoke-WebRequest -Uri "http://sim:8080" -Method Post -Body $JSON -ContentType "application/json"
        write-host $response
        

        $global:sim
    } catch {} 
} | out-null

doesn't give any response

Thanks in advance

**Comment by joeherwig** [comment]
Hi Seymur,

I'm sorry you're having trouble...
It's just a working draft for my rig.
There are two things you need to check:
1. Ensure that you change in https://github.com/joeherwig/portable-sim-panels/blob/master/simconnect/simconnect.ps1#L129 the host name to the proper one. 
2. take care that you have the proper simconnect installed and addressed via https://github.com/joeherwig/portable-sim-panels/blob/master/simconnect/simconnect.ps1#L12
I tried https://dl.dropboxusercontent.com/u/34075223/downloads/utils/SimConnect.msi and it worked within P3D V3.4.

Please let me know, whether this fixed your trouble. Thanks and regards,

Joe

**Comment by joeherwig** [comment]
@seymurkarimov: In the meanwhile i removed the powershell-stuff and moved all to node which uses a native node add-in. based on https://github.com/EvenAR/node-simconnect.
With this you should'nt get the trouble mentioned above because in this case you don't need any REST-Calls to a "servername" but the Server emits directly to the websockets where the clients are listening...

Due to this the adaption of the REST URI is obsolete and i close this bug.

btw: ensure that you're running node in 32-Bit mode for P3D v3 (and earlier as well as for FSX.)
